FROM --platform=$TARGETPLATFORM python:3.14-slim-bookworm
ARG TARGETPLATFORM
ARG BUILDPLATFORM

RUN apt-get update && \
    apt-get install -y gcc python3-dev libpq-dev curl && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

{{ .INSTALL_BUILD_TOOLS }}

WORKDIR /app
