// Code generated by dockerfile-metadata. DO NOT EDIT.

package debian

// Default Dockerfile (Dockerfilego)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.0"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "91960bf4fca3cdaebeab9e69e64372e6881b1e98a4a3c870cb9ff9a99e9ee756"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.0

# libbtrfs-dev is needed by podman go module
RUN apt-get update && \
  apt-get install -y git openssh-client libbtrfs-dev && \
  apt-get clean -y && \
  apt-get autoremove -y && \
  rm -rf /tmp/* /var/tmp/* && \
  rm -rf /var/lib/apt/lists/*

RUN go install github.com/pact-foundation/pact-go/v2@v2.4.1 && \
  pact-go -l DEBUG install && \
  go clean -cache && \
  go clean -modcache

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go clean -cache && \
  go clean -modcache
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
