// Code generated by dockerfile-metadata. DO NOT EDIT.

package debian

// Default Dockerfile (Dockerfilego)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.5"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "1e85e8fff6276d3e0b3d3d69e74d22bad97dae6f6f44334372c38e252dc2af47"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.5

# Note: libbtrfs-dev is not needed since we build with exclude_graphdriver_btrfs tag
RUN apt-get update && \
  apt-get install -y git openssh-client && \
  apt-get clean -y && \
  apt-get autoremove -y && \
  rm -rf /tmp/* /var/tmp/* && \
  rm -rf /var/lib/apt/lists/*

RUN go install github.com/pact-foundation/pact-go/v2@v2.4.1 && \
  pact-go -l DEBUG install && \
  go clean -cache && \
  go clean -modcache

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go clean -cache && \
  go clean -modcache
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
