// Code generated by dockerfile-metadata. DO NOT EDIT.

package goreleaser

// Default Dockerfile (Dockerfile.goreleaser-zig)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "v2.17.1"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "4f45d3f29233c888ef6be3e287ae80fa700658433eb906f7565109f60062b83c"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM goreleaser/goreleaser:v2.17.1
ARG ZIG_VERSION="0.17.0-dev.1609+11e2bb391"

RUN apk add --no-cache curl xz && \
    ZIG_ARCH=$(uname -m | sed 's/arm64/aarch64/' | sed 's/amd64/x86_64/') && \
    curl -L https://ziglang.org/builds/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz \
    | tar -xJ -C /usr/local && \
    ln -s /usr/local/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin/zig && \
    apk del curl xz && \
    rm -rf /var/cache/apk/*

# Verify Zig installation
RUN zig version
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
