FROM goreleaser/goreleaser:v2.15.2
ARG ZIG_VERSION=0.16.0

RUN apk add --no-cache curl xz && \
    ZIG_ARCH=$(uname -m | sed 's/arm64/aarch64/' | sed 's/amd64/x86_64/') && \
    curl -L https://ziglang.org/download/${ZIG_VERSION}/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz \
    | tar -xJ -C /usr/local && \
    ln -s /usr/local/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin/zig && \
    apk del curl xz && \
    rm -rf /var/cache/apk/*

# Verify Zig installation
RUN zig version
