// Code generated by dockerfile-metadata. DO NOT EDIT.

package alpine

// Default Dockerfile (Dockerfile_go)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.3-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "4a9ca95b1e23fc6c6cbdb48a1fc2640761110b15319b88d04009801e92615d9d"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.3-alpine

RUN apk --no-cache add git openssh-client && \
  rm -rf /var/cache/apk/*

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3 && \
  go clean -cache && \
  go clean -modcache
`

// chromium variant (Dockerfile_chromium_go)
const (
	// ImageVersionChromium is the golang version extracted from the Dockerfile
	ImageVersionChromium = "1.26.3-alpine"

	// DockerfileChecksumChromium is the checksum of the Dockerfile content
	DockerfileChecksumChromium = "e9221d40fec0889f7a9be30f62db46f52401c963b05e8876b54602557843c474"
)

// DockerfileContentChromium contains the embedded Dockerfile content
var DockerfileContentChromium = `FROM golang:1.26.3-alpine

RUN apk --no-cache add git openssh-client chromium && \
  rm -rf /var/cache/apk/*

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.11.3 && \
  go clean -cache && \
  go clean -modcache
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant, or "chromium" for chromium variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	case "chromium":
		return ImageVersionChromium, DockerfileChecksumChromium, DockerfileContentChromium
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
