// Code generated by dockerfile-metadata. DO NOT EDIT.

package alpine

// Default Dockerfile (Dockerfile_go)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.5-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "096a36b82ff5fb5374e293978cafc2ef2acd74dca11238cb8c034d61ae3d91f3"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.5-alpine

RUN apk --no-cache add git openssh-client && \
  rm -rf /var/cache/apk/*

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2 && \
  go clean -cache && \
  go clean -modcache
`

// chromium variant (Dockerfile_chromium_go)
const (
	// ImageVersionChromium is the golang version extracted from the Dockerfile
	ImageVersionChromium = "1.26.5-alpine"

	// DockerfileChecksumChromium is the checksum of the Dockerfile content
	DockerfileChecksumChromium = "d3696de6aee51d403bc2b27d88acc9d58d1d774952440b55edcd5d8bce9ff459"
)

// DockerfileContentChromium contains the embedded Dockerfile content
var DockerfileContentChromium = `FROM golang:1.26.5-alpine

RUN apk --no-cache add git openssh-client chromium && \
  rm -rf /var/cache/apk/*

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2 && \
  go clean -cache && \
  go clean -modcache
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant, or "chromium" for chromium variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	case "chromium":
		return ImageVersionChromium, DockerfileChecksumChromium, DockerfileContentChromium
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
