FROM golang:1.25.3-alpine

RUN apk --no-cache add git openssh-client && \
  rm -rf /var/cache/apk/*

RUN go install github.com/wadey/gocovmerge@latest && \
  go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest && \
  go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.4.0 && \
  go clean -cache && \
  go clean -modcache
