// Code generated by dockerfile-metadata. DO NOT EDIT.

package rust

// Default Dockerfile (Dockerfile.rust)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.93-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "ed2f4c38f3362e3187c5d1ed26dbed0a9b401010a76279b70d99713c9964b5a7"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM --platform=$TARGETPLATFORM rust:1.93-alpine
ARG TARGETPLATFORM
ARG BUILDPLATFORM

# Install basic build dependencies (openssl-dev + pkgconfig for reqwest/TLS)
RUN apk add --no-cache musl-dev openssl-dev openssl-libs-static pkgconfig

WORKDIR /app

# Verify Rust installation
RUN rustc --version && cargo --version
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
