// Code generated by dockerfile-metadata. DO NOT EDIT.

package rust

// Default Dockerfile (Dockerfile.rust)
const (
	// ImageVersion is the Rust version extracted from the Dockerfile
	ImageVersion = "1.83-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "94f403cbf07af2000a192624e73e52d5ff1ec512411e3706a3fe2f19f1ad33df"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM --platform=$TARGETPLATFORM rust:1.83-alpine
ARG TARGETPLATFORM
ARG BUILDPLATFORM

# Install basic build dependencies
RUN apk add --no-cache musl-dev

WORKDIR /app

# Verify Rust installation
RUN rustc --version && cargo --version
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
