// Code generated by dockerfile-metadata. DO NOT EDIT.

package debiancgo

// Default Dockerfile (Dockerfilego)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.6"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "aff1c2e54961c27359bb75433adfcd1f9e76e279fb8c22f1f1fd5895cedd0ca0"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.6

RUN apt-get update && \
    apt-get install -y clang build-essential \
    libssl-dev \
    gcc \
    libc6-dev \
    pkg-config \
    ca-certificates && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/*

# Note: libbtrfs-dev is not needed since we build with exclude_graphdriver_btrfs tag
RUN apt-get update && \
  apt-get install -y git openssh-client && \
  apt-get clean -y && \
  apt-get autoremove -y && \
  rm -rf /tmp/* /var/tmp/* && \
  rm -rf /var/lib/apt/lists/*

# RUN go install github.com/pact-foundation/pact-go/v2@v2.4.1 && \
#   pact-go -l DEBUG install && \
#   go clean -cache && \
#   go clean -modcache

ARG TARGETARCH
ENV CGO_ENABLED=1
ENV OPENSSL_DIR=/usr/include/openssl
ENV CGO_CFLAGS="-I/usr/include/openssl"
ENV CGO_LDFLAGS="-L/usr/lib/${TARGETARCH}-linux-gnu -lssl -lcrypto"
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
