// Code generated by dockerfile-metadata. DO NOT EDIT.

package debiancgo

// Default Dockerfile (Dockerfilego)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "1.26.0"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "3e7e39d2a079028a9e6dea0d3e67e21ff010abe81577977ed8395ccf7d465015"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM golang:1.26.0

RUN apt-get update && \
    apt-get install -y clang build-essential \
    libssl-dev \
    gcc \
    libc6-dev \
    pkg-config \
    ca-certificates && \
    apt-get clean -y && \
    apt-get autoremove -y && \
    rm -rf /tmp/* /var/tmp/* && \
    rm -rf /var/lib/apt/lists/*

# libbtrfs-dev is needed by podman go module
RUN apt-get update && \
  apt-get install -y git openssh-client libbtrfs-dev && \
  apt-get clean -y && \
  apt-get autoremove -y && \
  rm -rf /tmp/* /var/tmp/* && \
  rm -rf /var/lib/apt/lists/*

# RUN go install github.com/pact-foundation/pact-go/v2@v2.4.1 && \
#   pact-go -l DEBUG install && \
#   go clean -cache && \
#   go clean -modcache

ENV CGO_ENABLED=1
ENV OPENSSL_DIR=/usr/include/openssl
ENV CGO_CFLAGS="-I/usr/include/openssl"
ENV CGO_LDFLAGS="-L/usr/lib/aarch64-linux-gnu -lssl -lcrypto"
`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
