// Code generated by dockerfile-metadata. DO NOT EDIT.

package zig

// Default Dockerfile (Dockerfile.zig)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "3.24"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "3b8eaa7466bf4509e3f8783a4042553780c724d18357964f688be235fd66ac65"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM alpine:3.24
ARG ZIG_VERSION=0.17.0-dev.1609+11e2bb391

RUN apk add --no-cache curl xz && \
    ZIG_ARCH=$(uname -m | sed 's/arm64/aarch64/' | sed 's/amd64/x86_64/') && \
    curl -L https://ziglang.org/builds/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}.tar.xz \
    | tar -xJ -C /usr/local && \
    ln -s /usr/local/zig-${ZIG_ARCH}-linux-${ZIG_VERSION}/zig /usr/local/bin/zig

WORKDIR /app

# Verify Zig installation
RUN zig version`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
