// Code generated by dockerfile-metadata. DO NOT EDIT.

package alpine

// Default Dockerfile (Dockerfile)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "26-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "6ac882ec00cda20d884f7cd1c8e5f8bb2b6f2a482e6824cdac8adda26a2caa33"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM node:26-alpine

RUN apk --no-cache add \
      bash git openssh-client curl ca-certificates \
      go \
  && npm install -g @anthropic-ai/claude-code@latest \
  && rm -rf /var/cache/apk/* /root/.npm

WORKDIR /src

RUN go version`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
