// Code generated by dockerfile-metadata. DO NOT EDIT.

package alpine

// Default Dockerfile (Dockerfile)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "25-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "1795f5aa55c7cecc0e75b342d5b87871e5259559c507740ef25e6ab89cb3805d"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM node:25-alpine

RUN apk --no-cache add \
      bash git openssh-client curl ca-certificates \
      go \
  && npm install -g @anthropic-ai/claude-code@latest \
  && rm -rf /var/cache/apk/* /root/.npm

WORKDIR /src

RUN go version`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
