// Code generated by dockerfile-metadata. DO NOT EDIT.

package alpine

// Default Dockerfile (Dockerfile_claude)
const (
	// ImageVersion is the golang version extracted from the Dockerfile
	ImageVersion = "22-alpine"

	// DockerfileChecksum is the checksum of the Dockerfile content
	DockerfileChecksum = "df729a9658e22a80475b9bde9b11648b8a9e369b7b5a03d26bb97fa925a3e59f"
)

// DockerfileContent contains the embedded Dockerfile content
var DockerfileContent = `FROM node:22-alpine

RUN apk --no-cache add \
      bash git openssh-client curl ca-certificates \
      go \
  && npm install -g @anthropic-ai/claude-code@latest \
  && rm -rf /var/cache/apk/* /root/.npm

WORKDIR /src

RUN go version`

// GetDockerfileMetadata returns the metadata for the specified variant type.
// Pass empty string "" for default variant.
func GetDockerfileMetadata(variantType string) (version, checksum, content string) {
	switch variantType {
	default: // "" or any unknown type defaults to standard
		return ImageVersion, DockerfileChecksum, DockerfileContent
	}
}
