name: Release Protos2

on:
  push:
    branches:
      - main
    paths:
      - proto/**
      - protos2/**
  workflow_dispatch:
    inputs:
      tag:
        description: "tag to be released"
        required: true
        default: ""

concurrency:
  # Grouped by ref (branch/tag name) not to cancel other jobs running for other feature branches
  group: engine_ci_service_${{ github.ref }}
  # > cancel any currently running job or workflow in the same concurrency group
  # in case of multiple pushes to the same branch, we just need the latest, so cancel all previous
  cancel-in-progress: true

permissions:
  contents: write # for checkout
  id-token: write # for authenticating to Google Cloud Platform
  pull-requests: write # for updating pr

jobs:
  sub-module-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Get Next Version
        id: semver
        if: inputs.tag == ''
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
          prefix: protos2/
          noVersionBumpBehavior: silent
          skipInvalidTags: true
          maxTagsToFetch: 50
      - name: Create Tag
        uses: actions/github-script@v7
        with:
          script: |
            const {TAG} = process.env
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: `refs/tags/${TAG}`,
                sha: context.sha
            })
        env:
          TAG: ${{ inputs.tag == '' && steps.semver.outputs.next || inputs.tag }}
      - name: Update major and minor release tags
        uses: containifyci/.github/github-actions/update-semver@main
        with:
          tag_name: ${{ inputs.tag == '' && steps.semver.outputs.next || inputs.tag }}
          semver_prefix: protos2/v
        env:
          GITHUB_TOKEN: ${{ secrets.CONTAINIFYCI_RELEASE_TOKEN  }}
