name: Release Client

on:
  push:
    branches:
      - main
    paths:
      - client/**
  workflow_dispatch:
    inputs:
      tag:
        description: "tag to be released"
        required: true
        default: ""

concurrency:
  group: engine_ci_service_client${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # for checkout

jobs:
  sub-module-release:
    uses: ./.github/workflows/sub-module.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      module: client
